<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cc42d543-bc9f-4b18-8372-30990ef64672}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
		ESTACION: FB_Estacion;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ESTACION();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>