<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ac507533-9318-47ac-91b7-94a836fda366}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Estacion: FB_Estacion;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Estacion();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>